apiVersion: v1
kind: Service
metadata:
  name: {{ include "finplan.frontend.fullname" . }}
  labels:
    {{- include "finplan.frontend.labels" . | nindent 4 }}
  annotations:
    {{- include "finplan.syncWave" .Values.argocd.syncWaves.workloads | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "finplan.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
